name: Build fornecedores-service

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v4

      - name: Instalar o Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar com o Maven
        run: mvn -B clean package --file fornecedores-service/pom.xml
